apiVersion: apps/v1
kind: Deployment
metadata:
  name: suppoting(delivery)
  labels:
    app: suppoting(delivery)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suppoting(delivery)
  template:
    metadata:
      labels:
        app: suppoting(delivery)
    spec:
      containers:
        - name: suppoting(delivery)
          image: "username/suppoting(delivery):latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
