apiVersion: v1
kind: Service
metadata:
  name: suppoting(delivery)
  labels:
    app: suppoting(delivery)
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: suppoting(delivery)