apiVersion: apps/v1
kind: Deployment
metadata:
  name: core(order)
  labels:
    app: core(order)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core(order)
  template:
    metadata:
      labels:
        app: core(order)
    spec:
      containers:
        - name: core(order)
          image: "username/core(order):latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
